### ISSUE TITLE
When table popup is not configured to show Popup Title and/or when Popup

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#113]
1. Go to app 
http://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=e8a635f816554f1693282516b574dba5

2. Click on a feature (Example: McDonald)

3. Fill out the form without entering 'Name' field. 

4. Notice in comments, there is no horizontal line

Note: In webmap the related table for this layer is configured to show 'Name' field in title. If title is left blank in popup configuration, the same behavior is seen in app

![image](https://cloud.githubusercontent.com/assets/3836616/10742951/4a4611c2-7bed-11e5-8bea-a34059b9e6fb.png)

**Comment by allisonmuise** [comment]
@skrishn : Does the same behavior exist on production?

**Comment by MikeTschudi** [comment]
Yes; it's an attribute of popup displays. If the popup's title field is empty, either because no title was configured or because it only contains an attribute and that attribute's value is empty, then both the title area and the horizontal line are hidden by the JSAPI popup renderer.

An enhancement to make it easier to read these comments is to apply a border around each comment. E.g., the following screenshot shows a 1-pixel gray border around each item with a 1-pixel vertical overlap so that the lines are not doubled at comment boundaries:
![image](https://cloud.githubusercontent.com/assets/2125181/10743489/b14bcab2-7bf0-11e5-973f-ee114dff6db7.png)

**Comment by allisonmuise** [comment]
I don't think the border is necessary - it makes for a lot of lines when the title is there. The line is part of the popup title - if users want the lines they can configure a popup title.
