### ISSUE TITLE
available votes fields should be limited to numeric fields

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#118]
The current list includes all field types, including OIDS, GUIDS, date fields, and text fields which are not valid for the required functionality.

**Comment by MikeTschudi** [comment]
It's already limited to integers, so this may be a platform issue:
```
"fields": [{
    "supportedTypes": ["esriFieldTypeSmallInteger", "esriFieldTypeInteger"],
    "multipleSelection": false,
    "fieldName": "itemVotesField",
    "label": "Votes Field",
    "tooltip": "Numeric field in the selected layer for tracking the votes received for each feature."
}]
```

**Comment by MikeTschudi** [comment]
Changed to new configuration type label via commit 2810ed66f900a2d1d37e5b5e60348ad00859c61d

**Comment by MikeTschudi** [comment]
@allisonmuise The AGOL configureApp converts the field type to lowercase before checking its value everywhere except in one place: the place where the supported types are extracted from the configuration. Because the comparison at this point is with a camel-cased "layerAndFieldSelector", Crowdsource Polling's all-lowercase tag "layerandfieldselector" doesn't match and so the supported types are ignored.

It seems better to change Crowdsource Polling's configuration to camel case to match the other templates that use this field type rather than to get the configureApp changed to add that extra toLowercase call.

**Comment by allisonmuise** [comment]
yes, this is a good idea

**Comment by allisonmuise** [comment]
@MikeTschudi : I am still seeing fields of all types in the votes field selection parameter on devext. Could you take another look at this?

**Comment by allisonmuise** [comment]
update - needs config content updated in template

**Comment by allisonmuise** [comment]
verified
