### ISSUE TITLE
Submit button disappears on hitting space in comment fields (if marked required)

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#124]
http://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourcePolling/index.html?appid=f1be2bf0ee9f4b0f8fd37197c744746a

Click comment button

When entering a value in comment field with 'more than one word and with space', notice that the submit button disappears on hitting space and reappears on typing a text

**Comment by MikeTschudi** [comment]
App is using the regexp validation pattern "\\S([\\S\\s]*\\S)?" to use Dojo dijit validation as a way to indicate that leading and trailing whitespace wasn't valid.  This is an error, because as one types a sentence, each time that one enters a space, the whole input becomes invalid until the next non-space character is entered.

**Comment by allisonmuise** [comment]
@skrishn : has this been verified?

**Comment by skrishn** [comment]
yes. verified
