### ISSUE TITLE
Cannot submit comments when service contains multiple layers and related features are not in index 0

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#128]
When using a service with multiple layers, only one of which participates in a relationship with a table, the related feature layer must be in index position 0 in order to submit comments to it's table.

The order of layers in the AGOL map has no impact.

**Comment by MikeTschudi** [comment]
I believe that line 181 in js/lib/LayerAndTableMgmt should use `tablerelate.relatedTableId` instead of `tablerelate.id` even though it is referring to its related feature layer. Currently, block is
```
array.some(commentTable.relationships, lang.hitch(this, function (tablerelate, i) {
    if (tablerelate.id === this._itemLayer.layerId) {
        tableKeyField = tablerelate.keyField;
        return true;
    }
    return false;
}));
```
Because the condition fails, the `tableKeyField` variable is not being set; this field is what helps to tie a comment back to its feature layer.

The problem occurs when the related feature layer does not have an id of 0--regardless of how many or how few feature layers are in the webmap--because `tablerelate.id` is 0.  In one of the failing test cases, the sole feature layer's id is 1 and the sole table's is 5.

**Comment by allisonmuise** [comment]
@MikeTschudi : Which branch did this get checked into?

**Comment by MikeTschudi** [comment]
master

**Comment by MikeTschudi** [comment]
Moved fix to 'develop' branch

**Comment by allisonmuise** [comment]
verified
