### ISSUE TITLE
Cannot enter date/tiem in comments

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#129]
Repro steps using a layer with a date field:

1) Open the item details page for the layer. In the Tables section, click the small down arrow beside the comment table name. Choose Time Settings, and enable time of the date field.

2) Add the layer to a map and open the popup setting for the table. 

3) Click the Configure Attributes link and choose the date field. Set the date format to one of the options that allows enabling time on the popup (eg 12/21/1997). Enable time and choose a format.

4) Save the popup and save the map.

5) Share the map using the Polling template. Note that the comment form does not allow for input of time.

**Comment by MikeTschudi** [comment]
It appears that it is not necessary to change the table's time settings in item details because a date field remains of type `esriFieldTypeDate` whether or not this setting has been used. The setting is for supporting a different type of app: one which has a time slider and can filter features based on time.

The popup is necessary, however, because at least some fields in the popup can have a `format` parameter, and that parameter contains a `dateFormat` parameter for date fields. This latter parameter takes values such as `shortDate` (e.g., "12/21/1997") and `shortDateLongTime24` (e.g., "12/21/1997" + "18:00:00").

At this time, the app doesn't use the format field for any data types. There are eight date+time formats currently defined in the popup attribute configuration panel, so recognizing any of these in the popup for a field is enough to know that the field should have a time dijit along with the date dijit:

1. `shortDateShortTime`
2. `shortDateShortTime24`
3. `shortDateLongTime`
4. `shortDateLongTime24`
5. `shortDateLEShortTime`
6. `shortDateLEShortTime24`
7. `shortDateLELongTime`
8. `shortDateLELongTime24`

(Only date formats `shortDate` and `shortDateLE` support time display.)

It may be possible to control the time dijit a bit; the Dojo documentation is scanty. If we can, there are four time suffix formats currently defined for the popup:
1. `-ShortTime`  (e.g., 6:00 PM)
2. `-LongTime`  (e.g., 6:00:00 PM)
3. `-ShortTime24`  (e.g., 18:00)
4. `-LongTime24`  (e.g., 18:00:00)

It's even less clear if we can control the formatting for the date dijit; if we can, there are eight date-only formats currently defined for the popup:

1. `shortDate`  (e.g., 12/21/1997)
2. `shortDateLE`  (e.g., 21/21/1997)
3. `longMonthDayYear`  (e.g., December 21, 1997)
4. `dayShortMonthYear`  (e.g., 21 Dec 1997)
5. `longDate`  (e.g., Sunday, December 21, 1997)
6. `longMonthYear`  (e.g., December 1997)
7. `shortMonthYear`  (e.g., Dec 1997)
8. `year`  (e.g., 1997)

`shortDate` and `shortDateLE` also serve as prefixes for date+time formats.

**Comment by MikeTschudi** [comment]
Implementation in commit:

If one of the time suffixes is present for a date field in a comment table's popup, the date dijit is split into a date and time dijit pair. The format of the time dijit display uses AM/PM for the `-ShortTime` and `-LongTime` suffixes and 24-hour for the `-ShortTime24` and `-LongTime24` suffixes:

![image](https://cloud.githubusercontent.com/assets/2125181/14356700/c177549e-fc9a-11e5-8bf9-c2459134afa3.png)

![image](https://cloud.githubusercontent.com/assets/2125181/14357031/eb6b8dfa-fc9b-11e5-88ef-b170c431c378.png)

("Date" happens to be the field name in this case.)

Otherwise, the normal full-width date dijit is used:

![image](https://cloud.githubusercontent.com/assets/2125181/14356750/f677089c-fc9a-11e5-8dbd-71ba6c1e3c28.png)

There is a single JSON value for the field whether or not time display is enabled in the popup. The difference with time display is that

* if time display is not enabled for field, the field's time is the UTC equivalent of midnight local time, e.g., `"Date":"2015-04-07T07:00:00.000Z"`
* if time display is enabled for a field, the field's time is a combination of the date dijit's date value and the time dijit's time value in the UTC equivalent of local time, e.g., `"Date":"2015-04-07T15:12:00.000Z"`; the AM/PM versus 24-hour formatting in the popup has no effect in the JSON, which always uses 24-hour time

**Comment by allisonmuise** [comment]
@MikeTschudi 
Thanks! What you've described above looks exactly like what I was hoping we could do.

**Comment by allisonmuise** [comment]
@MikeTschudi : Is this in devtopia for me to test? If so, can you assign it to me?

**Comment by allisonmuise** [comment]
verified
