### ISSUE TITLE
Allow comments to be hidden

### ISSUE THREAD

**Issue by MarkCooperSDC** [Esri/crowdsource-polling#140]
Hi

This is my first post on github so please forgive me if this is not the correct place to ask this!

This template is ideal for some public consultation work we are doing. However, when a member of the public has made a comment, we require this not to be displayed on the app (at least until it is moderated). Is there a way to prevent submitted comments from showing and just show the comment count?

Also, if possible, can an email be sent to the customer acknowledge receipt of their comment?

I dont have any coding experience myself but we do have a developer who has some knowledge of apsi if needed.

Many thanks

**Comment by allisonmuise** [comment]
@MarkCooperSDC : 
Yes! Both functions are possible, although the number of comments will reflect the number of comments that have been approved and email notification does require more than just AGOL.

To send email notification when features are created, you will need to set up GeoEvent Server.

To moderate comments, set a filter on the comment table so that no comments meet the filter requirement when they are submitted, but can be updated to meet the requirement after review. There are many ways to do that, but here is one potential workflow:

1. Add a domain with YES & NO values to your GDB, and add a field (eg PUBLICVIEW) to your comment table that uses this domain. Set the default value of the field to NO.

2. Overwrite your existing layer. Overwriting will let you keep the same map & app you've already configured, but heed the warning about deleting any changes you've made to the layer....you may want to publish a new layer, and create a new map & app instead.

3. Set a filter on the comment table layer in the map that will feed your Polling app so that only table records with a value of YES are displayed.

4. Verify that your new field is not listed as Editable or Displayed in the popup configuration of the table layer. You don't want your comment submitters to be able to update this value, and there's no reason for them to be able to view it, either.

4. Submit a comment - it shouldn't be visible in the app because only comments with a value of YES will appear and all comments are created with a value of NO.

5. Update the value of your new field using the layer's item details page, a Crowdsource Manager app (recommended), etc so that the value of the field is now YES. Check the Polling app - the comment should now be visible.

Also - While this is the correct place to ask questions in GitHub, posting questions like this to GeoNet allows other users to search for and find your questions as well as the answers that were provided. You might also get responses from other users who have suggestions about what has worked for them :)

**Comment by MarkCooperSDC** [comment]
Thanks. I have got that bit to work exactly how I need it.

Unfortunately, I don't think I will be able to use it as I need to show another layer on the map and this appears to prevent comments being collected. Even if it did allow for this, I manage to get that working, there doesn't appear to be a way to add a legend file. I don't suppose you know if there is a way round this?

I will post a question on GeoNet as well, as you suggested.

**Comment by allisonmuise** [comment]
@MarkCooperSDC : Thanks! If you @mention me in geonet, I'll reply there with info re: legend and displaying additional layers.

**Comment by MarkCooperSDC** [comment]
@allisonmuise - is your username tthe same on geonet?

**Comment by allisonmuise** [comment]
@Allison_Muise should find me.
