### ISSUE TITLE
Request\Question: Passing in a feature parameter via the URL

### ISSUE THREAD

**Issue by tcprocto** [Esri/crowdsource-polling#145]
Currently, is there a way to pass in the objectid or some other feature parameter to zoom directly to that feature via the URL?

Thanks,
Troy Proctor

**Comment by allisonmuise** [comment]
@tcprocto Currently there is not, but it's an interesting idea. I'll put this on the list to consider for our release later this year.

**Comment by tcprocto** [comment]
Is there a portion of code I might be able to add to get the URL parameter functionality to work?

Thanks,
Troy Proctor

**Comment by tcprocto** [comment]
I didn't mean to close that.

**Comment by MikeTschudi** [comment]
@tcprocto: There are two steps to adding a custom URL parameter:

1. Add the parameter's keyword to the config/templateConfig.js file (see #146 )
2. Modify the app to do something with the supplied parameter

For step 2 for passing the objectid, e.g., `http://server/crowdsource-polling/?id=9`, one could insert some behavior after the app finishes setting up that
1. Queries by that object id
2. Amends the result with the infoTemplate (the key to the formatting of the item in its detailed view)
3. Posts an internal message to select the item

Whenever one searches for an app item, clicks on its shape on the map, or clicks on its title in the summary list, the app posts an internal message with the selected item. Another part of the app is listening for that message, and when it receives it, it shows the detailed view for that item. We can hook into that same mechanism once we have found the item by its object id. It's best to wait until the app is set up so that the listeners are set up.

The following is a rough **unsupported** sketch showing how this might be done; the changes are in js/main.js; it's in (branch id-url-param)[https://github.com/Esri/crowdsource-polling/tree/id-url-param].

```
//----- Done -----
console.log("app is ready");

// Attempt to go to an item specified as a URL parameter
if (this.config.id) {
    var id = Number.parseInt(this.config.id), _this = this;
    if (!isNaN(id)) {
        require(["esri/tasks/query", "esri/tasks/QueryTask"], function(Query, QueryTask) {
            var query, queryTask, featureLayer = _this.map._layers[_this.map.graphicsLayerIds[0]];
            queryTask = new QueryTask(featureLayer.url);
            query = new Query();
            query.objectIds = [id];
            query.returnGeometry = true;
            query.outFields = ["*"];

            queryTask.execute(query, function (results) {
                if (results && results.features && results.features.length > 0) {
                    var item = results.features[0];
                    item._layer = featureLayer;
                    item._graphicsLayer = featureLayer;
                    topic.publish("itemSelected", item);
                }
            }, function (error) {
                console.log(error);
            });
        });
    }
}
```

The method for getting the feature layer from the webmap is very rough; I wouldn't use it without a lot of testing and verification--there might easily be a better way. But once you have that feature layer, you can set up the QueryTask as well as provide an infoTemplate for the details display.

**Comment by allisonmuise** [comment]
merge branch id-url-param for 4.4

**Comment by agcallis** [comment]
@MikeTschudi  Thanks you so much for the ID URL Param addition, It works great for Google Chrome. Do you have any ideas why it wouldn't work in Internet Explorer 11? The application open and loads in Internet Explorer 11 but it doesn't zoom to the id like it does with google chrome. It just stays at full extent.

**Comment by MikeTschudi** [comment]
@agcallis Thank you for bringing this up.  It didn't work in IE 11 because of an error on my part:  I used the newer `Number.parseInt` function to parse the id parameter rather than the older global `parseInt` function, and IE 11 doesn't support the former.  I changed the app to use `parseInt`, and now this feature works for Chrome 53, Firefox 49, IE 11, and Edge.

The update is in branch id-url-param.

**Comment by allisonmuise** [comment]
@MikeTschudi What is the URL syntax to see this enhancement?

**Comment by MikeTschudi** [comment]
http://server/crowdsource-polling/?id=objectid

**Comment by allisonmuise** [comment]
AGOL syntax:
http://ORG.arcgis.com/apps/CrowdsourcePolling/index.html?appid=GUID&id=OBJECTID

where
ORG is the organization
GUID is the app id
OBJECTID is the OID of the feature

If the OID is not found the app opens to show the full list of items

**Comment by allisonmuise** [comment]
@MikeTschudi : Is the fix to make this work with Kelly's panel parameters in and ready to test?

**Comment by allisonmuise** [comment]
verified
