### ISSUE TITLE
Adding Custom URL Parameters

### ISSUE THREAD

**Issue by agcallis** [Esri/crowdsource-polling#146]
Is there away to add in extent or feature layer parameter into URL?

I see in the TemplateConfig.js the following:
  //This option demonstrates how to handle additional custom url parameters. For example
  //if you want users to be able to specify lat/lon coordinates that define the map's center or
  //specify an alternate basemap via a url parameter.
  "urlItems": [
  ]
Does this allow for extent or feature parameters ??
Or is there a way to modify the code?

**Comment by allisonmuise** [comment]
Duplicate #145

**Comment by MikeTschudi** [comment]
@agcallis:  Yes, this is part of the process of getting the app to use a custom URL parameter.

The app is based on the (application-boilerplate-js 3.x)[https://github.com/Esri/application-boilerplate-js/tree/master]. The app does some initial setup and then passes control to the custom part of the app. One of the tasks supplied by the boilerplate is the screening of URL parameters: any custom URL parameters listed in `urlItems` and present in the URL will be added to the configuration object passed to the custom part of the code.

So in order to customize for initial extent or feature ids, one would first add the desired URL parameter keyword(s) into the array, e.g.,
```
  "urlItems": [
    "id"
  ],
```
If the keyword is present in both the list and the URL (e.g., `.../?...&id=6`), main.js will have a config string property with the keyword name (e.g., `this.config.id`) that contains the value associated with the keyword in the URL (e.g., "6").

The next task is to modify the custom part of the app to look for and use that configuration item.
