### ISSUE TITLE
Map always zooms in when clicking features on the map

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#152]
It appears that when you click on a feature that has a popup up associated with it (in this case that means the attribute values appear in the text panel to the right (at least as this version is configured) the map also zooms in.  If you then click on the same feature again, or another feature in the then current map extent, the map zooms in again.  

(LA via @NikkiGolding email 8/18)

**Comment by MikeTschudi** [comment]
Unable to reproduce using JSAPI 3.18 (the version when this issue was reported), 3.19, or 3.20dev using the app's try-it-live webmap, which has a custom attribute display popup.

**Comment by allisonmuise** [comment]
@MikeTschudi : I can still repro this behavior using apps on production.

**Comment by MikeTschudi** [comment]
@allisonmuise figured out that it occurs with point layers.

If the point is not highlighted when clicked, it occurs; e.g., http://esri.github.io/crowdsource-polling/?appid=fcb943b54f1243e0899d8a53fdc59ae7

If the point is highlighted when clicked, it does not occur; e.g., http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=fcb943b54f1243e0899d8a53fdc59ae7

JSAPI version doesn't affect this; the app appears to have been fixed with the addition of highlighting the selected item on the map (31b3b0a88b48a3470fc54aa5d7e6d6e1a1e49af4; 10/25/2016 09:37:30).

**Comment by allisonmuise** [comment]
@MikeTschudi : perhaps I'm not understanding. Shoudl this have been fixed in October? I'm still seeing the issue on prd...

**Comment by MikeTschudi** [comment]
@allisonmuise, do you see it with single repeat clicks on a feature?  Double-clicks zoom the map; October's work only fixed the single repeat clicks on a feature; it did not affect single clicks on different, unselected features.

**Comment by MikeTschudi** [comment]
@allisonmuise, what should the behavior be?

With lines & polygons, it's easy and consistent even with repeats:  expand the bounds of the item by 175% and zoom to that expansion.  Points, without an extent, have nothing that permits consistent behavior, so the app simply zooms in by 2 regardless of the current zoom level.  (Repeat clicks on the same item don't do this because points are highlighted by a temporary symbol, and that symbol intercepts the click, which is also why clicking on a selected item doesn't bring up the item details.)

Perhaps don't do any zooming for point features?

**Comment by allisonmuise** [comment]
I'm just selecting features from the list - not actually clicking the map at all.

Yes, let's go with no zooming at all.

**Comment by MikeTschudi** [comment]
App follows same path whether a feature is selected in a map or in a list.  Zoom has been removed for features without extents (i.e., points).

**Comment by allisonmuise** [comment]
@MikeTschudi  - The app is no longer zooming, but panning appears to have been turned off as well. The app can maintain the same zoom level, but the extents should pan to center on the selected feature.

**Comment by allisonmuise** [comment]
verified
