### ISSUE TITLE
Show search at top of list view in phone mode

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#153]
scott moore 8/24/2016

**Comment by allisonmuise** [comment]
the search widget is currently only visible on desktops and tables. In smartphone view, add the search widget between the title header an the feature list.

![2-28-2017 1-53-45 pm](https://cloud.githubusercontent.com/assets/2752195/23436063/0d927ed8-fdbe-11e6-9446-aa1a1ea1ab1e.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

After adding the search control on the list view, would you like us to remove the search control from the map in smartphone view? Or it will be available at both the places please confirm.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Search should be available in both locations.

**Comment by CTLocalGovTeam** [comment]
@MikeTschudi  @allisonmuise 

We would like to confirm the following approach to implement this enhancement:
- We are planning to create separate instance of the search dijit for the itemList panel.
- For screens greater than 640px of width search bar(in item list panel) will be hidden, and based on the screen size if it is less than 640px search bar will be displayed in item list panel.
- On window resize we need to resize the width of the search control to fit in the panel width.

You can see the implementation on this [link](http://csslesxi9-vm3.cybertech.com/crowdsource_polling/crowdsource-polling-search-demo/)

Please let us know your thoughts on this approach.

In addition to this we have few following questions:
- After selecting result from the search control of item list panel what should be the behavior?
- Should the application navigated to map view, as result would have been selected on map

**Comment by MikeTschudi** [comment]
@CTLocalGovTeam, very nice implementation, and because the app has separate panels for the map and list, it seems the most economical and clean approach.

While it's @allisonmuise's decision, I'm happy to offer an opinion on the questions. :-)

After selecting the result from the search control of item list panel, it seems to me that it should open the selected item's details page. I have picked an item while searching in the list context. While the result could be to highlight it in the list, that wouldn't tell me anything useful--the list is not meaningful. Rather than have me click again, just show me the item. I wouldn't want to jump to the map because that would be an unexpected change of context.

This is similar to the behavior in the map view where after selecting the result, the map jumps to the selected item and highlights it. I have picked an item while searching in the map context and now I see its location on the map.

---

A pair of questions from me, please:

* @CTLocalGovTeam, when the browser window is narrowed, can the lag between the browser resize and the list's search dijit resize be reduced, or the dijit hidden during the lag?  When the browser window is widened, the dijit is smoothly extended, but when it is narrowed, it wraps until resized:
![image](https://cloud.githubusercontent.com/assets/2125181/24463003/57139dc8-145a-11e7-9559-4720399326e6.png)

* @allisonmuise, is it OK that the search term is not copied between the two dijits? The difference between these two shots of the same session is a few pixels of screen resize, or a toggle between map view and list view when <640px. 
![image](https://cloud.githubusercontent.com/assets/2125181/24462656/653ffc62-1459-11e7-9b16-50afeffb33ac.png)
![image](https://cloud.githubusercontent.com/assets/2125181/24462661/692e5116-1459-11e7-986c-6929739c8043.png)

**Comment by CTLocalGovTeam** [comment]
@MikeTschudi 

User can select result of geocoder or other layers form the search control, so in case of selecting geocoder or other layers result we cannot show the details panel.
so what should we do in this case?

>>@CTLocalGovTeam, when the browser window is narrowed, can the lag between the browser resize and the list's search dijit resize be reduced, or the dijit hidden during the lag? When the browser window is widened, the dijit is smoothly extended, but when it is narrowed, it wraps until resized:

CT: We can hide the dijit during the lag.

@allisonmuise We are awaiting for your inputs on this please let us know your thoughts.

**Comment by MikeTschudi** [comment]
@CTLocalGovTeam, thank you--I'd missed the geocoder/other layer case. I see how showing the map for these when searching from the list view is required; otherwise, the search appears to do nothing. 

Despite the different behavior, however, if one is searching the polled layer from the list view, I would still propose that the details view opens for the selected result.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
I would suggest the following:
- when the selected search result is a feature in the Polling layer, the app should display the details for that feature. 
- When the selected search result is from another layer with a popup configured (per #223 ), the app should display the details for that feature. 
- If neither of these cases are met, the app should display the map, pan/zoom to the location, and indicate the location of the search result. 

@MikeTschudi I'm not worried about maintainng the search terms when resizing between mobile and desktop views as this is a testing workflow and not one that users are likely to encounter while actually using the app.

**Comment by MikeTschudi** [comment]
@allisonmuise, note that maintaining search terms affects the bigger case of toggling between map view and list view when <640px--no resizing. So in the third case, if I've searched for Cooper's Hawk Winery in the map view, then go to the list view and search for 345 11th Ave, Naperville, Illinois, USA, my map view will go to 345..., but the search box will still have Cooper's....

![image](https://cloud.githubusercontent.com/assets/2125181/24619629/7bb96de4-184f-11e7-8743-84f462e471af.png)  
![image](https://cloud.githubusercontent.com/assets/2125181/24619679/ab27005a-184f-11e7-8ab3-f83c900c26d4.png)

**Comment by allisonmuise** [comment]
@MikeTschudi Thanks for the further explnation.

@CTLocalGovTeam What's LOE to sync the search terms between the widgets?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I have updated the descriptions of the use cases in my previous comment. Let's proceed with syncing the search terms as described during this morning's meeting.

**Comment by allisonmuise** [comment]
@MikeTschudi Please merge this into the develop branch and devtopia

**Comment by MikeTschudi** [comment]
@allisonmuise done

**Comment by allisonmuise** [comment]
verified

**Comment by MikeTschudi** [comment]
This fix needs to be re-verified following the fix of a bug (#188) introduced by it

**Comment by allisonmuise** [comment]
@MikeTschudi have you verified this? If not, @skrishn could you take a look?

**Comment by allisonmuise** [comment]
![image](https://user-images.githubusercontent.com/2752195/30505556-3fa0f996-9a2a-11e7-8318-9e58ae109837.png)
grey space showing alongside search bar

**Comment by allisonmuise** [comment]
grey box only shows when only 1 search source is configured

**Comment by MikeTschudi** [comment]
Traced to original commit of feature (1ac6acb953d017d6d424ece70357eec90572cf87). The behavior is an attribute of the JSAPI Search dijit, which was not designed to fill the width of a container, so apps and widgets have to manage it themselves.

**Comment by allisonmuise** [comment]
@MikeTschudi  woo!! thanks!! looks god in testing. @skrishn please run auto tests on polling first thing monday AM
