### ISSUE TITLE
Search widget displays 'layer' search when not configured in webmap

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#156]
By default webmap setting is set to search 'By Address'  but  search widget in Crowdsource Polling displays a drop-down to search by 'Layer' also

![image](https://cloud.githubusercontent.com/assets/3836616/18728905/40b4f9ea-8004-11e6-820e-05c255b07638.png)

If this is a default behavior then the "Search In" drop-down values should display Layer Name as it is in the webmap example: Polling Data- Poly and not with a Field Name as in the screenshot. 

Note: Issue not seen in basic viewer.

**Comment by ashishchoure** [comment]
@allisonmuise 

We are not able to reproduce this issue. The changes made to webmap settings such as "Search by Address" and "Search by layer" are honored in the application.
Here is the screenshot : 
1. Search by Address
![image](https://user-images.githubusercontent.com/5525972/49145941-03555c00-f327-11e8-90cf-1226ae81a02b.png)

 
2. Search by Layer
![image](https://user-images.githubusercontent.com/5525972/49145879-d6a14480-f326-11e8-8bc8-5ececb1f84f2.png)

Could you please share the webmap link if the issue is still reproducible. Or let us know if we are missing anything from our side.

**Comment by ashishchoure** [comment]
@allisonmuise 

Could you please confirm if you are still able to reproduce the issue?. This will help us in estimating the ticket.

**Comment by allisonmuise** [comment]
@ashishchoure I am still able to repro this issue. I suspect that it is related to the True/False/Null issues we have seen with other map settings. In this case, layer search has never been configured, and I am seeing the layers in the drop down for the app search widget.
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=b9e4d6a7256f419c9baafde21e20fcd4
![12-5-2018 4-54-07 pm](https://user-images.githubusercontent.com/2752195/49553922-d963e280-f8ae-11e8-9763-2ff7c4c207cb.png)
![12-5-2018 4-54-26 pm](https://user-images.githubusercontent.com/2752195/49553923-d963e280-f8ae-11e8-919d-3a8f98a44fbe.png)

**Comment by ashishchoure** [comment]
@allisonmuise 

Your observation is correct. You will see all the layers in search dijit in crowd source polling until you configure the **"Search by Layer"** property for the first time. Once it is configured, the search dijit will honor **"Search by Layer"** configuration for no layer/one layer/all layers.

However, the existing code in polling says that if the **"Search by Layer"** properties are never configured for a webmap, then show all the valid layers in search dijit (Due to this we see all the layers in search).

Do you want us to change this implementation and remove all the layers from search djiit if the **"Search by Layer"** property is never configured for a webmap?

![image](https://user-images.githubusercontent.com/5525972/49577696-ff03f100-f96d-11e8-9c91-0ac99723488b.png)

**Comment by allisonmuise** [comment]
verified
