### ISSUE TITLE
ENH-000099975 Ability to specify a single locator when configuring Crowdsource Polling template and other templates that use locators or the search widget

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#160]
Include the ability to specify one locator when configuring Crowdsource Polling Template instead of app inheriting all locators in organization's Utility Services Settings
Salesforce ID: ENH-000099975
Salesforce Submitter: Krista McPherson
Salesforce Submit Date: 10/10/2016 9:41 AM
Salesforce Bug Type: Product
Salesforce Severity: Medium
Repro Data: \esri.com\sf_filestore\PRD\Attachments\Defects\ENH-000099975
Work Around: 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.

-User creates new Crowdsource Polling App from Template
-Maintains all default settings
-Currently, the application inherits all locators from the organization's Utility Services Settings (see images)
Locators available in app
User-added image
Locators in organization's Utility Services Settings
User-added image
-Only way to specify one locator in a template would be to delete all other locators in settings, which is unreasonable
-This issue exists with all templates that use locators/search widget
-The ability to do this is already available in Web AppBuilder (see image) and customer would like to see this available in templates as well
User-added image
1. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)

Would allow users who have multiple custom locators in their organization's Utility Services Settings to specify locators when using app templates
1. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer's workflow or business?)

End users of the application would get the best geocoding/search results as determined by the application creators without end users having to know which locator to specify
Product: ArcGIS Online
Functional Category: ArcGIS Online Application Templates
Client Platform: (n/a)
Version Found: N/A
Planned Version Fixed: (n/a)
Comment: (n/a)

**Comment by allisonmuise** [comment]
arcgis-portal-app-templates/#1347

**Comment by allisonmuise** [comment]
Add the geocoder configuration parameter to the config panel. The selected geocoders should be used by the search widget in the app.

Example: Basic Viewer
![8-15-2017 1-36-07 pm](https://user-images.githubusercontent.com/2752195/29337130-1c3ff1b4-81c5-11e7-999c-082cd17efe7a.png)

**Comment by allisonmuise** [comment]
@MikeTschudi : note milestone :)

**Comment by MikeTschudi** [comment]
By its original requirements, the app uses the search settings in its webmap.

* If Find Locations is not checked, there's no search box.
* If it is checked,
  * If neither By Layer nor By Address is checked, there's no search box.
  * If only By Layer is checked and one or more of the app's webmap layers are configured, they are available in the search box
  * If only By Address is checked, geocoder(s) are available in the search box:
    * if oauthappid and the sharing URL are configured, the org geocoders are used
    * otherwise, the Esri World Geocoder is used
  * If both By Layer and By Address are checked, both the configured layers and the geocoder(s) are available in the search box.

I don't see a way to merge this with the Viewer-style configuration item because the webmap settings program and the web app settings program can't intercommunicate.  The only option appears to completely replace the webmap-style configuration with the the Viewer-style configuration; @allisonmuise?

**Comment by allisonmuise** [comment]
@MikeTschudi  I understand, we will defer this until a major update.
