### ISSUE TITLE
Check for objectIdField in addition to OID types when filtering out form attributes

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/crowdsource-polling#164]
An bug in service publishing for when an object id field is assigned at publish time causes its type to sometimes be esriFieldTypeInteger instead of esriFieldTypeOID.  

App filters out OID fields using field types, and fields with type esriFieldTypeInteger are considered valid form fields.  Workaround for now is for app to check the feature layer's objectIdField as well as field types.

**Comment by allisonmuise** [comment]
@MikeTschudi : Can you just just display all fields set as editable in the popup configuration? Primary key fields can't be set as editable so that should prevent them from displaying:
![11-17-2016 8-52-55 am](https://cloud.githubusercontent.com/assets/2752195/20398732/62256d82-aca3-11e6-8632-03b8052aa214.png)

**Comment by allisonmuise** [comment]
@MikeTschudi : Is this in and ready for testing?

**Comment by allisonmuise** [comment]
verified
