### ISSUE TITLE
Display message when attachment fails

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#166]
When an attachment cannot be added to a comment, display a message at the top of the comments panel with light yellow background, and dark yellow/orange text/outline : x of y attachments could not be added.

See Reporter for formatting of 'warning' message window.

**Comment by MikeTschudi** [comment]
crowdsource-reporter failed upload:
![image](https://cloud.githubusercontent.com/assets/2125181/21907216/7b6f0cca-d8c3-11e6-96c1-a63bf0947539.png)

**Comment by MikeTschudi** [comment]
Implementation follows the crowdsource-reporter pattern:
![image](https://cloud.githubusercontent.com/assets/2125181/21946091/b6846780-d993-11e6-9f31-0c84614434ef.png)    ![image](https://cloud.githubusercontent.com/assets/2125181/21946194/2618c870-d994-11e6-9f86-48aacae85b48.png)

Note:  IE 11 doesn't support the file upload if one is using http instead of https.  We can probably detect this and hide the attachments upload UI.  @allisonmuise, preference?

**Comment by allisonmuise** [comment]
perfect! Yeah...let's detect and hide if possible.

**Comment by MikeTschudi** [comment]
Updated via commit d4479ce5fbdb7c27575fd7619e2baa83525410ae

**Comment by allisonmuise** [comment]
verified on FF, Chrome, IE 11
