### ISSUE TITLE
Sign in dialog panel not displaying correctly

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-polling#179]
Currently noticed in devext

![image](https://cloud.githubusercontent.com/assets/3836616/26129801/9cb47980-3a46-11e7-8302-a8212360916a.png)

**Comment by MikeTschudi** [comment]
Reproducible with production 3.18, 3.19, 3.20.

Traced to commit 381be0baee4bb050307ea25c39db9ad1ba4cc722:
```
381be0baee4bb050307ea25c39db9ad1ba4cc722 is the first bad commit
commit 381be0baee4bb050307ea25c39db9ad1ba4cc722
Author: ashishch <CTLocalGovTeam@cybertech.com>
Date:   Wed Apr 5 17:56:21 2017 +0530

    Resolved Github Issue #148
    
    #148 : update help panel to match reporter
```

@allisonmuise, can CT look at this?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam The help panel is displaying well with your changes, but they seem to have also afftected the sign in panel. Could you please take a look to see why this panel is not displayign correctly, and submit a code drop with the fix ASAP.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The Sign-in dialog got messed up because of changes in help dialog. We have made some changes in sign-in dialog to make it look similar to help dialog.

Here is the screenshot : 
![image](https://cloud.githubusercontent.com/assets/2959186/26398412/09c9e428-4097-11e7-8445-c732a20097a5.png)

This way both dialog's will have similar look and feel. Also, this will maintain consistency within the application.

Please let us know if this looks good or we need to show the older Sign-in dialog.

**Comment by allisonmuise** [comment]
Looks good!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I liked how, in the screenshot above, the rest of the app was greyed out, like it is with the help panel. In the code that was delivered last week, I'm not seeing the app greying out behind the panel, and unlike with the help, I am still able to click on the surrounding app elements.

Without the greyed-out background the panel gets a bit lost on the screen. Could you please add this functionality?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We have updated the sign in panel to show greyed-out background. 

![image](https://cloud.githubusercontent.com/assets/2959186/26627614/b64e949c-4618-11e7-8a7b-3ea40fff82a1.png)

**Comment by allisonmuise** [comment]
Looks good!
