### ISSUE TITLE
Revise attachment dialog on side panel

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/crowdsource-polling#187]
Implement more subtle feedback when an attachment is uploaded.  Could implement something similar to the Crowdsource Reporter.  Maybe just color change - green when successful, red when failed. 

![screen shot 2017-08-18 at 4 16 52 pm](https://user-images.githubusercontent.com/2379330/29541681-b0b99484-86a3-11e7-855e-48d9a6a7e6e9.png)

**Comment by MikeTschudi** [comment]
Crowdsource Reporter uses feedback along the lines of
![image](https://user-images.githubusercontent.com/2125181/30074360-27ddc53e-9226-11e7-9c93-e8be202ed315.png)
![image](https://user-images.githubusercontent.com/2125181/30074369-2dbbe03a-9226-11e7-86ae-ade876cba979.png)
![image](https://user-images.githubusercontent.com/2125181/30074376-31fe69b0-9226-11e7-94da-1c4aee9caecc.png)

Crowdsource Polling uses the light blue "info" color shown in the screenshot above for success (Crowdsource Reporter uses the "success" color) and the "danger" color that Crowdsource Polling uses for failures.  (Color scheme is from the bootstrap library that both apps use.)

These messages are useful because color alone can be hard to see; e.g., here's what the "success" color looks like under three types of color blindness:
![image](https://user-images.githubusercontent.com/2125181/30073280-1408b4aa-9222-11e7-97b8-e4e53d054c1a.png)

@ScottOppmann, may I have more details of your request, please.

**Comment by ScottOppmann** [comment]
@MikeTschudi - I did not think about the challenges with the color but do think we should be consistent.  Ie.  Green if successful, red if not.  It also looks like the font used in Polling is different than Reporter and would suggest we be consistent.  So, I would suggest we amend Polling's info message so it matches the color and style of Reporter.  Make sense?

**Comment by MikeTschudi** [comment]
Sounds clear; thanks!

**Comment by allisonmuise** [comment]
@MikeTschudi  Is this ready for me to test? At a quick glance, it appears to be working...

**Comment by allisonmuise** [comment]
verified on devext
