### ISSUE TITLE
selection polygon doesn't match feature boundaries

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#191]
https://geonet.esri.com/thread/201598-crowdsource-polling-mismatched-boundaries-upon-zoom

When the Crowdsource polling app zooms to my project the automatic blue selection (i.e. project boundary) on the interactive map doesn't match the actual boundary of the project (see attachment). Once the user clicks on the actual project or within the project boundary (as they are polygons) the blue selection boundary fixes itself. We are worried when we roll this out to the public the mismatched blue selection will confuse them as to where the actual boundary of the project lies. Please advise.

**Comment by allisonmuise** [comment]
Dev strategy discussed with @MikeTschudi : Stop using maxAllowableOffset for query, and perform a second query when a feature is selected. Slightly higher overhead on the individual feature queries, but no increase to overall app loading overhead. Also avoids hard-coding a tolerance value into the app.

**Comment by MikeTschudi** [comment]
In addition to the second query, the app now does an extra zoom just before the query.

It zooms to the selected item's extent, but then backs out one zoom level; this extra zoom sets the feature layer's simplification parameter so that the second query gets the desired precision.

The zoom to extent does not set the parameter, so using it alone causes the second query to continue to return overly simplified coordinates until the user does a manual zoom.

**Comment by allisonmuise** [comment]
@MikeTschudi Is this ready for testing in devext?

**Comment by MikeTschudi** [comment]
@allisonmuise, not yet--devext hasn't been built since the check-in

**Comment by allisonmuise** [comment]
verified
