### ISSUE TITLE
BUG-000139056 If a web map has map notes it will cause the list in the Crowdsource Polling application to never load

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-polling#258]
Bug Summary:

- If a user has map notes in their web map and they try to create a Crowdsource Polling application the list element of the application will never load (during configuration and the published version).
- Expected behavior: Users should be able to include map notes in their map without it breaking the list functionality in the Crowdsource Polling application

.
Sample Data:

These items have been added to the DevTest account in ArcGIS Online in the bug folder.

- Point Layer (hosted feature layer).
   - Link: https://ess.maps.arcgis.com/home/item.html?id=ac7182efd9bb40c6bfbe96d48594d53f
- Web Map (web map).
   - Link: https://ess.maps.arcgis.com/home/item.html?id=529bf4b8921748c598eb524684d60246
- Crowdsource Polling Application (application).
   - Link: https://ess.maps.arcgis.com/home/item.html?id=9106208b202540779cd63c35787175a7

Work Around:

- Save the Map Notes as a layer. This will be a feature layer.
- Publish the Map Note feature layer. This will be a hosted feature layer.
- Remove the original Map Notes "layer" from the web map. Add the hosted feature layer version to the web map and save it.

The list issue in the Crowdsource Polling application is being caused by the Map Notes that are included in the web map. If you save the map note "layer" as a layer (hit the three dots), then go to the item details page of the new layer, and choose the publish option you can create a hosted feature layer version which will work.

Go back to your web map, remove the map notes "layer" and then add the new hosted feature layer version that was published. More than one layer will come into the map and you can just remove those that are unnecessary. Resave the map and the list should now load fine!

**Comment by ashishchoure** [comment]
@aparveen 

We have analyzed the issue and here are our findings : 

**Case 1:** 
- The map notes are added as a feature collection. In the code, we check for a feature layer before clearing the existing definition expressions (Please refer to Image 1). 
- Since the feature collection doesn't have `layerObject ` property, the code breaks and we do not see the feature list in the side panel. 
- We can resolve the issue by adding one more check for the feature collection layer. (So the updated logic will be to check for feature layer which is not of a type feature collection. Please refer to Image 2: line no 1418 should be updated to check for feature layers which are not of type feature collection)

Image 1 : 
![image](https://user-images.githubusercontent.com/5525972/122400448-5a7cb400-cf99-11eb-866d-5b595c538d5f.png)

Image 2 : 
![image](https://user-images.githubusercontent.com/5525972/122400553-72ecce80-cf99-11eb-8753-3e4b99efb78e.png)



**Case 2:**
- While going through the code we also observed that, if the feature layer is not configured then we always fall back to the layer which is present at the 0th index in the web map. (Please refer to Image 3)
- However, there could be a case that the layer present at the 0th index is not a feature layer. In this case, the application will not work as a polling application requires a feature layer.
- Instead of using the 0th layer, we should get the first feature layer in the web map and use the same. This way the application will always work.

Image 3: 
![image](https://user-images.githubusercontent.com/5525972/122402745-66697580-cf9b-11eb-9ec7-3d0f35e65e0c.png)


@MikeTschudi Please let us know your thoughts on the above approach.

**Comment by MikeTschudi** [comment]
@ashishchoure, thank you for the detailed investigation (I'm sorry that I missed the GH notification). Your changes look great.

**Comment by ashishchoure** [comment]
### Dev Checklist

Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS change?​ | No |   | ​
Required Backward compatibility​? | No |   |  
Required 508​? | No |   |  
Need Sanitize?​ | No |   |  

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | Yes
Have Runtime changes?​ | Yes
Impact on RTL | No
Check for valid feature layer | <li>The application should check for a valid configured feature layer in the web map</li><li>If the configured layer is not present in the web map or it is not a valid feature layer then the application should use the first available feature layer from the web map.
No valid feature layer is available in the web map | <li> If feature layer is not available in the web map then a message should be displayed in the panel in order to notify the user.</li>

**Comment by ashishchoure** [comment]
@MikeTschudi 

- Just came across a case when there is no valid feature layer present in the web map.
- We are planning to show a message in the panel and this way users will be notified about the actual scenario.
- In addition to this, we have made a small change in the code to capture the scenario where an unmatching feature layer is configured. Instead of comparing the `iOpLayer `variable with `opLayers.length` we have created a boolean variable `isValidFeatureLayer`. (Please refer the screenshot)
- If configured feature layer in not present in the web map then the flag value will be `false` and then we will use the first available feature layer from the web map.
- If no feature layers are present in the web map then we will show the message in the panel.

![image](https://user-images.githubusercontent.com/5525972/124068818-d3c7dc80-da58-11eb-9ef8-4cecfcfaf2cb.png)

Just wanted to update you about all the scenarios to make sure all of us are on the same page and we on our side are not missing anything.

**Comment by MikeTschudi** [comment]
@ashishchoure, looks good!  @aparveen, OK with need for error message to user?

**Comment by aparveen** [comment]
@MikeTschudi @ashishchoure I am good with change.

**Comment by skrishn** [comment]
verified in qa
