### ISSUE TITLE
BUG-000138148 Sidecar scrolls down when selecting features from an embedded Crowdsource Polling app.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-polling#268]
**Steps:**

1. Create a Crowdsource Polling Application
2. Embed the application to a web page that has substantial information/space where you would need to scroll down to review the entire page's contents.
3. When reviewing the embedded application, select a feature on the Crowdsource Polling Application
4. BUG: When selecting one feature then another, you will notice the application begin scrolling down. It will continue scrolling until you have reached the end of the web page.

**Additional Notes:**

- Screen recording attached to Defect
- Not browser specific
- Crowdsource Polling Application: https://ess.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=ad0cbde1a9b94bc993091d0ee40f29d9
- Embedded Web Page Test 1: https://storymaps.arcgis.com/stories/3ea2a4fe0ee84d98b36eddd410232ca7
- Embedded Web Page Test 2: https://codepen.io/oevans/pen/RwpgrZr

**Comment by aparveen** [comment]
I was able to repro it with initial feature selection when the app is embedded in Experience Builder

**Comment by sumitzarkar** [comment]
@aparveen 

## RootCause and Solution
- We are able to reproduce this issue and have identified the root cause. 
- This is due to the **nodeToMakeVisible.scrollIntoView** function call
- We have found the solution to fix this issue and will deliver it in next code drop

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime Impacted areas | 1. Whenever the ItemList is show <br/>2. Whenever item from the list is selected to see the details <br/> 3. Whenever comments button is clicked

**Comment by skrishn** [comment]
verified in qa

**Comment by skrishn** [comment]
The issue is not reproducible outside of my machine.
