### ISSUE TITLE
UX on app load

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#74]
If a layer has not yet been configured, the app currently loads with the following message: "Unable to create map: Unable to fully load map: Item feature layer is missing"

Loading the application/displaying a map in the application should not depend on having a layer picked in the configuration panel.

Either:

1st choice: load the first editable layer by default

2nd choice: leave the right-side panel blank with a message (in the panel space) that says "Please configure the application to use an editable layer"

**Comment by MikeTschudi** [comment]
Webmap with no feature layers:
![image](https://cloud.githubusercontent.com/assets/2125181/9554849/de26adaa-4d7d-11e5-9d6a-bf0ad5ffd184.png)

Webmap with unconfigured feature layer; picks first layer:
![image](https://cloud.githubusercontent.com/assets/2125181/9554844/cf3a66a6-4d7d-11e5-8d6c-bc467e483538.png)
Features in this first layer are displayed using its popup, just as with a configured feature layer. In this example, since the votes fields is not configured, votes are not displayed or accepted.

"Editable" may be too restrictive. The try-it version, e.g., is not editable but it does accept votes.

**Comment by allisonmuise** [comment]
Yup, this looks good. I had 'editable' on the brain from Reporter :)
verified on local copy of the app.
