### ISSUE TITLE
Search widget doesn't honor web map search configuration

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-polling#78]
Search parameters are configured in the item details of a web map including whether search shoudl include layers (and if so which ones and which fields) and/or a geocode service.

The search widget should honor these settings and the search hint.

**Comment by allisonmuise** [comment]
search layers are honored.
search hint is not currently honored. moving to 3.10

**Comment by MikeTschudi** [comment]
There is some important background about AGOL hints and the way that the app handles the hint.

If one creates a new webmap with a searchable feature layer, the webmap AGOL item will show that the "Find Locations" Application Settings is enabled by default with hint text "Place or Address" (internationalized using the org user's language setting, not the browser's language setting) and searching by address enabled, but not searching by layer. These defaults and display are part of the AGOL UI--they are not stored with the webmap and are not available to the app if no changes are made.

For this case, the app assumes that Search dijit is enabled for searching addresses and all feature layers. (Note how the latter is different than the AGOL item UI.) For address searching, the app uses the default settings of the Search dijit, which are to use the Esri geocoder with the hint "Find address or place" (internationalized using the browser's language setting). For feature layer searching, the dijit is asked to scan the map for feature layers to add. It adds them with an empty hint which cannot be overridden.

Note that the hint "Find address or place" is fixed in the Search dijit if one is searching everything configured in the dijit--it does not appear to be changeable. What one can change, however, is the hint for each of the individual searches. So if one uses the dropdown arrow to select to search only the Esri geocoder, e.g., one gets the hint configured for the geocoder. If the default hint is not desired for this geocoder, we can add the AGOL UI string "Place or Address" (internationalized) into the app to override the default. This should be safe because any change in the AGOL UI to the hint string will trigger the next case.  Similarly, for the feature layers, if the "Place or Address" hint is important, the app can do the scanning for feature layers itself and manually add them into the dijit with the customized hint.

If one makes any saved change to the Find Locations property--even, e.g., simply by disabling Address searching, saving, reenabling, and then saving again--the "Find Locations" information gets written to the webmap and the app can use it. The app can now be controlled via these settings: enabling/disabling the dijit, setting the organization's geocoders list, choosing the layers to be searchable. The hint configured in the AGOL UI is used for each of the feature layers configured to be searchable, but, again, it only appears when that layer is exclusively selected as the search target. As with the default case, the hint is not used for any of the geocoders--default or custom--because they come with hints, but this can be changed if desired.

**Comment by allisonmuise** [comment]
cool! Thanks for explaining this.
